eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
      registerWithEureka: true
      fetchRegistry: true
      
spring:
   application:
      name: Microservice1